[custom.all.ilex-fasta]
type = "local"
path = "fasta"
ipkg = "ilex-fasta.ipkg"
test = "test/test.ipkg"

[custom.all.ilex]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-ilex.git"
commit = "latest:simplify_parser"
ipkg   = "ilex.ipkg"

[custom.all.ilex-streams]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-ilex.git"
commit = "latest:simplify_parser"
ipkg   = "streams/ilex-streams.ipkg"
